name: CI

on:
  push:
    branches:
      - main  # Change to your default branch or any branch you want to monitor
  pull_request:
    branches:
      - main  # This ensures tests run on PRs targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'  # Specify the Python version you want to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      run: |
        python -m unittest discover -s .venv -p '*_test.py' -v
